version: '3.7'
services:
  mysql:
   image: mariadb:10.5.5-focal
   restart: always
   environment:
     TZ: Asia/Shanghai
     MYSQL_ROOT_PASSWORD: 111111
     MYSQL_USER: 'febs-cloud'
     MYSQL_PASS: '111111'
     MYSQL_ROOT_HOST: '%'
   command:
     --character-set-server=utf8mb4
     --collation-server=utf8mb4_general_ci
     --explicit_defaults_for_timestamp=true
     --lower_case_table_names=1
     --max_allowed_packet=128M
     --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
     #--default-authentication-plugin=mysql_native_password
   volumes:
     - ./sql:/docker-entrypoint-initdb.d
     - ./conf:/etc/mysql/conf.d
     - ./data:/var/lib/mysql
   privileged: true
   ports:
   - 3306:3306
   networks:
     febs-cloud-bridge:
       ipv4_address: 172.20.0.8
networks:
  febs-cloud-bridge:
    driver: bridge
    external:
      name: febs-cloud-bridge
